[project]
name = "uv-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.0",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
